repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
#        entry: venv/bin/python3.11 -m pylint  # Para Linux/Mac
        entry: venv\Scripts\python3.11.exe -m pylint  # Para Windows
        language: system
        types: [python]
        args:
          [
            "-rn",  # Apenas exibir mensagens
            "-sn",  # Não exibir a pontuação
            "--rcfile=.pylintrc",  # Link para o seu arquivo de configuração
            "--load-plugins=pylint.extensions.docparams",  # Carregar uma extensão
          ]
